### ISSUE TITLE
Error: exists; not overwriting

### ISSUE THREAD

**Issue by l1br3** [semiromid/compress-images#14]
Your module seems to try to write several times the same file.
All my directories are deleted everytime before running the script so it's impossible the file already exists in the destination directory.

```bash
 File from: /home/libre/Documents/Knights/pvp/8axis/sprites/spritesheets/thrust5.png
 File to: /home/libre/Documents/Knights/pvp/8axis/sprites/compressed/thrust5.png
 Compression algorithm: [pngquant]
{ Error: Command failed: /home/libre/dev/knights.io/node_modules/pngquant-bin/vendor/pngquant --quality=20-50 -o /home/libre/Documents/Knights/pvp/8axis/sprites/compressed/thrust5.png /home/libre/Documents/Knights/pvp/8axis/sprites/spritesheets/thrust5.png
  error: '/home/libre/Documents/Knights/pvp/8axis/sprites/compressed/thrust5.png' exists; not overwriting

    at ChildProcess.exithandler (child_process.js:273:12)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Socket.stream.socket.on (internal/child_process.js:353:11)
    at Socket.emit (events.js:180:13)
    at Pipe._handle.close [as _onclose] (net.js:538:12)
  killed: false,
  code: 15,
  signal: null,
  cmd: '/home/libre/dev/knights.io/node_modules/pngquant-bin/vendor/pngquant --quality=20-50 -o /home/libre/Documents/Knights/pvp/8axis/sprites/compressed/thrust5.png /home/libre/Documents/Knights/pvp/8axis/sprites/spritesheets/thrust5.png' }

```

**Comment by l1br3** [comment]
My bad, stupid mistake with Promises.
