### ISSUE TITLE
[pngquant] cannot open folder if its name contain cyrille

### ISSUE THREAD

**Issue by semiromid** [semiromid/compress-images#38]
pngquant - Не сохраняет изображение если имя директории указано кириллицей. 
Судя по всему эта проблема pngquant, но нужно будет проверить, и возможно нужно будет её обновить.

> 'Starting compress images'
> -----------------------------------
>  File from: src/img/новая/lice.png
>  File to: build/img/новая/lice.png
>  Compression algorithm: [pngquant]
> { Error: Command failed: J:\Разные файлы\compress-images\node_modules\pngquant-b
> in\vendor\pngquant.exe --quality=20-50 -o build/img/новая/lice.png src/img/новая
> /lice.png
>   error: cannot open src\img\новая\lice.png for reading
> 
>     at ChildProcess.exithandler (child_process.js:294:12)
>     at ChildProcess.emit (events.js:198:13)
>     at maybeClose (internal/child_process.js:982:16)
>     at Socket.stream.socket.on (internal/child_process.js:389:11)
>     at Socket.emit (events.js:198:13)
>     at Pipe._handle.close (net.js:606:12)
>   killed: false,
>   code: 2,
>   signal: null,
>   cmd:
>    'J:\\Разные файлы\\compress-images\\node_modules\\pngquant-bin\\vendor\\pngqu
> ant.exe --quality=20-50 -o build/img/новая/lice.png src/img/новая/lice.png' }
>  [Error] Your file was not compressed!!!
>  [Error] You can see log to:./log/compress-images
> -----------------------------------
> 'Compress images completed'
> 'Console will be close after [20] seconds...'
>

**Comment by semiromid** [comment]
https://github.com/kornelski/pngquant/issues/317
